name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include: 
        - os: Linux
          image: ubuntu-latest

        - os: Linux
          image: ubuntu-latest
          target: aarch64-unknown-linux-gnu
          cross: true

        - os: Linux
          image: ubuntu-latest
          target: armv7-unknown-linux-gnueabihf
          cross: true

        - os: MacOS
          image: macOS-latest

        - os: MacOS
          image: macOS-latest
          target: aarch64-apple-darwin
          test_cargo_args: --no-run

        - os: Windows
          image: windows-latest

        - os: Windows
          image: windows-latest
          target: x86_64-pc-windows-gnu

    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Restore
      id: cache_restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}
        restore-keys: |
          cargo-${{ runner.os }}-${{ matrix.target }}-

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.65.0
          target: ${{ matrix.target }}
          override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: ${{ matrix.target && format('--target={0}', matrix.target) }}
        use-cross: ${{ matrix.cross }}

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.target && format('--target={0}', matrix.target) }} ${{ matrix.test_cargo_args }}
        use-cross: ${{ matrix.cross }}

    - name: Cache save
      uses: actions/cache/save@v3
      if: ${{ always() }}
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}
